### THIS IS AN EXAMPLE OF OVERRIDE FOR DOCKER-COMPOSE (for Linux)
### Copy this code in your docker-compose.override.yml

version: "3"

services:

  php:
    environment:
      PHP_FPM_CLEAR_ENV: "no"
## Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
#      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
#      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
#      PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
      # Linux correct permission files.
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby

  nginx:
    environment:
      # Linux correct permission files.
      NGINX_USER: wodby

  apache:
    environment:
      # Linux correct permission files.
      APACHE_USER: wodby
      APACHE_GROUP: wodby

  mariadb:
    # Expose port of database
    ports:
      - 3306:3306
